/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as AdminHistoryRouteImport } from './routes/admin.history'
import { Route as AdminImportRouteImport } from './routes/admin.import'
import { Route as AdminPrizesRouteImport } from './routes/admin.prizes'
import { Route as AdminSettingsRouteImport } from './routes/admin.settings'
import { Route as AdminWheelsRouteImport } from './routes/admin.wheels'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminHistoryRoute = AdminHistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => AdminRoute,
} as any)
const AdminImportRoute = AdminImportRouteImport.update({
  id: '/import',
  path: '/import',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPrizesRoute = AdminPrizesRouteImport.update({
  id: '/prizes',
  path: '/prizes',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSettingsRoute = AdminSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AdminRoute,
} as any)
const AdminWheelsRoute = AdminWheelsRouteImport.update({
  id: '/wheels',
  path: '/wheels',
  getParentRoute: () => AdminRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/auth': typeof AuthRoute
  '/admin/history': typeof AdminHistoryRoute
  '/admin/import': typeof AdminImportRoute
  '/admin/prizes': typeof AdminPrizesRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/wheels': typeof AdminWheelsRoute
  '/admin/': typeof AdminIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/admin/history': typeof AdminHistoryRoute
  '/admin/import': typeof AdminImportRoute
  '/admin/prizes': typeof AdminPrizesRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/wheels': typeof AdminWheelsRoute
  '/admin': typeof AdminIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/auth': typeof AuthRoute
  '/admin/history': typeof AdminHistoryRoute
  '/admin/import': typeof AdminImportRoute
  '/admin/prizes': typeof AdminPrizesRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/wheels': typeof AdminWheelsRoute
  '/admin/': typeof AdminIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/auth'
    | '/admin/history'
    | '/admin/import'
    | '/admin/prizes'
    | '/admin/settings'
    | '/admin/wheels'
    | '/admin/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/admin/history'
    | '/admin/import'
    | '/admin/prizes'
    | '/admin/settings'
    | '/admin/wheels'
    | '/admin'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/auth'
    | '/admin/history'
    | '/admin/import'
    | '/admin/prizes'
    | '/admin/settings'
    | '/admin/wheels'
    | '/admin/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  AuthRoute: typeof AuthRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/history': {
      id: '/admin/history'
      path: '/history'
      fullPath: '/admin/history'
      preLoaderRoute: typeof AdminHistoryRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/import': {
      id: '/admin/import'
      path: '/import'
      fullPath: '/admin/import'
      preLoaderRoute: typeof AdminImportRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/prizes': {
      id: '/admin/prizes'
      path: '/prizes'
      fullPath: '/admin/prizes'
      preLoaderRoute: typeof AdminPrizesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/settings': {
      id: '/admin/settings'
      path: '/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AdminSettingsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/wheels': {
      id: '/admin/wheels'
      path: '/wheels'
      fullPath: '/admin/wheels'
      preLoaderRoute: typeof AdminWheelsRouteImport
      parentRoute: typeof AdminRoute
    }
  }
}

interface AdminRouteChildren {
  AdminHistoryRoute: typeof AdminHistoryRoute
  AdminImportRoute: typeof AdminImportRoute
  AdminPrizesRoute: typeof AdminPrizesRoute
  AdminSettingsRoute: typeof AdminSettingsRoute
  AdminWheelsRoute: typeof AdminWheelsRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminHistoryRoute: AdminHistoryRoute,
  AdminImportRoute: AdminImportRoute,
  AdminPrizesRoute: AdminPrizesRoute,
  AdminSettingsRoute: AdminSettingsRoute,
  AdminWheelsRoute: AdminWheelsRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  AuthRoute: AuthRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
